/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelCamera.Camera;
import modelCamera.CameraFR;
import modelCamera.HoaDon;
import modelCamera.HoaDonFr;


/**
 *
 * @author Admin
 */
public class QLHoaDon extends javax.swing.JFrame {
    
    HoaDonFr frhd = new HoaDonFr();
    List<HoaDon> lhd=new ArrayList<>();
    SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
    CameraFR fr = new CameraFR();

    /**
     * Creates new form HoaDon
     */
    public QLHoaDon() {
        initComponents();
        setLocationRelativeTo(null);
        open();
        
    }
    public void open() {
        frhd.readfile();
        Tablehd();
    }
    
    public void Tablehd(){
        DefaultTableModel model = (DefaultTableModel) tbhd.getModel();
         model.setRowCount(0);
        for (HoaDon hd : frhd.getallHoaDon()) {
            Object[] rowData = new Object[7];
            rowData[0] = hd.getMahoadon();
            rowData[1] = date.format(hd.getNgayxuat());
            rowData[2] = hd.getTenkh();
            rowData[3] = hd.getTensp();
            rowData[4] = hd.getGia();
            rowData[5] = hd.getSoluong();
            rowData[6] = hd.toString();
            //up table
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmahd = new javax.swing.JTextField();
        txtngayxuathd = new javax.swing.JTextField();
        txttenkh = new javax.swing.JTextField();
        txttencr = new javax.swing.JTextField();
        txtgia = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhd = new javax.swing.JTable();
        btntkhd = new javax.swing.JButton();
        btnrshd = new javax.swing.JButton();
        btndelhd = new javax.swing.JButton();
        btnfixhd = new javax.swing.JButton();
        btnsavehd = new javax.swing.JButton();
        btnsorthdaz = new javax.swing.JButton();
        btnsorthdza = new javax.swing.JButton();
        jlbtc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Hóa Đơn");
        jLabel1.setToolTipText("");

        jLabel2.setText("Mã Hóa Đơn       :");

        jLabel3.setText("Tên Khách Hàng :");

        jLabel4.setText("Ngày Xuất            :");

        jLabel5.setText("Tên Camera         :");

        jLabel6.setText("Giá                         :");

        jLabel7.setText("Số Lượng              :");

        txttenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenkhActionPerformed(evt);
            }
        });

        txttencr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttencrActionPerformed(evt);
            }
        });

        tbhd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Xuất", "Tên Khách Hàng", "Tên Camera", "Giá", "Số Lượng", "Tổng Tiền"
            }
        ));
        tbhd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbhd);

        btntkhd.setText("Tìm Kiếm");
        btntkhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntkhdActionPerformed(evt);
            }
        });

        btnrshd.setText("reset");
        btnrshd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrshdActionPerformed(evt);
            }
        });

        btndelhd.setText("Xóa");
        btndelhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelhdActionPerformed(evt);
            }
        });

        btnfixhd.setText("Sửa");
        btnfixhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfixhdActionPerformed(evt);
            }
        });

        btnsavehd.setText("Lưu");
        btnsavehd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavehdActionPerformed(evt);
            }
        });

        btnsorthdaz.setText("Sắp Xếp A-Z");
        btnsorthdaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsorthdazActionPerformed(evt);
            }
        });

        btnsorthdza.setText("Sắp Xếp Z-A");
        btnsorthdza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsorthdzaActionPerformed(evt);
            }
        });

        jlbtc.setText("tc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbtc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtgia, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                            .addComponent(txttencr)
                                            .addComponent(txtsoluong))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnsorthdaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnfixhd)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnsavehd))
                                            .addComponent(btnsorthdza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtmahd, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                            .addComponent(txttenkh, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtngayxuathd, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnrshd)
                                                .addGap(18, 18, 18)
                                                .addComponent(btndelhd))
                                            .addComponent(btntkhd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(14, 14, 14))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btntkhd))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngayxuathd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnrshd)
                    .addComponent(btndelhd))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttencr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfixhd)
                    .addComponent(btnsavehd))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsorthdaz)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsorthdza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jlbtc)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void reset() {
        txtmahd.setText("");
        txtngayxuathd.setText("");
        txttenkh.setText("");
        txttencr.setText("");
        txtgia.setText("");
        txtsoluong.setText("");
    }
    
    private void btnrshdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrshdActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnrshdActionPerformed

    private void btnsorthdzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsorthdzaActionPerformed
        // TODO add your handling code here:
        frhd.sortza();
        Tablehd();
        frhd.writefile();
    }//GEN-LAST:event_btnsorthdzaActionPerformed

    public boolean chek(){
        if(txtmahd.getText().isEmpty()||txtngayxuathd.getText().isEmpty()
                ||txttenkh.getText().isEmpty()||txttencr.getText().isEmpty()
                ||txtgia.getText().isEmpty()||txtsoluong.getText().isEmpty()
                ){
            return false;
        } return true;
    }
    public HoaDon getModel()throws ParseException{
        HoaDon hd = new HoaDon();
        hd.setMahoadon(txtmahd.getText());
        hd.setNgayxuat(date.parse(txtngayxuathd.getText()));
        hd.setTenkh(txttenkh.getText());
        hd.setTensp(txttencr.getText());
        hd.setGia(Double.parseDouble(txtgia.getText()));
        hd.setSoluong(Double.parseDouble(txtsoluong.getText()));
        return hd;
    }
    private void btnsavehdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavehdActionPerformed
        // TODO add your handling code here:
        if(chek()){
            try {
                HoaDon hd = getModel();
                if(frhd.addhd(hd)>0){
                    Tablehd();
                    frhd.writefile();
                    jlbtc.setText("Cập Nhập Thành Công");
                }
            } catch (ParseException ex) {
                Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnsavehdActionPerformed

    private void tbhdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhdMouseClicked
        // TODO add your handling code here:
         int id = tbhd.rowAtPoint(evt.getPoint());
        String mahd = tbhd.getValueAt(id, 0).toString();
        HoaDon hd = frhd.getHoaDonid(mahd);
        find(hd);
    }//GEN-LAST:event_tbhdMouseClicked

    private void txttenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenkhActionPerformed

    private void btnfixhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfixhdActionPerformed
        // TODO add your handling code here:
        if(txtmahd.getText().isEmpty()){
            
        }else{
            try {
                HoaDon hd= getModel();
                if(frhd.edit(hd)>0){
                    Tablehd();
                    frhd.writefile();
                    jlbtc.setText("Cập Nhập Thành Công");
                }
            } catch (ParseException ex) {
                Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnfixhdActionPerformed

    private void txttencrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttencrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttencrActionPerformed
    
    private void btndelhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelhdActionPerformed
        // TODO add your handling code here:
        if(chek()){
            if(frhd.delhd(txtmahd.getText())>0){
                frhd.writefile();
                Tablehd();
            }
        }
    }//GEN-LAST:event_btndelhdActionPerformed
    
     public void find(HoaDon hd) {
        txtmahd.setText(hd.getMahoadon());
        txtngayxuathd.setText(date.format(hd.getNgayxuat()));
        txttenkh.setText(hd.getTenkh());
        txttencr.setText(hd.getTensp());
        txtgia.setText(Double.toString(hd.getGia()));
        txtsoluong.setText(Double.toString(hd.getSoluong()));

    }
    private void btntkhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntkhdActionPerformed
        // TODO add your handling code here:
        if(txtmahd.getText().isEmpty()){
            jlbtc.setText("Chưa Nhập");
        }else{
            HoaDon h = frhd.find(txtmahd.getText());
            if(h!=null){
                find(h);
            }else{
                JOptionPane.showMessageDialog(this, "Không Tìm Thấy");
            }
        }
    }//GEN-LAST:event_btntkhdActionPerformed

    private void btnsorthdazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsorthdazActionPerformed
        // TODO add your handling code here:
        frhd.sortaz();
        Tablehd();
        frhd.writefile();
    }//GEN-LAST:event_btnsorthdazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelhd;
    private javax.swing.JButton btnfixhd;
    private javax.swing.JButton btnrshd;
    private javax.swing.JButton btnsavehd;
    private javax.swing.JButton btnsorthdaz;
    private javax.swing.JButton btnsorthdza;
    private javax.swing.JButton btntkhd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbtc;
    private javax.swing.JTable tbhd;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtmahd;
    private javax.swing.JTextField txtngayxuathd;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttencr;
    private javax.swing.JTextField txttenkh;
    // End of variables declaration//GEN-END:variables

}
